#! /bin/sh

pkill sxhkd
pkill dunst
pkill compton

sxhkd &
dunst &
compton --config ~/.config/compton/compton.conf &

feh -z --no-fehbg --bg-fill "$HOME/Downloads/purple-jungle.jpg"

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier alt
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
