#! /bin/sh

pkill sxhkd
pkill dunst
pkill picom
pkill polybar

sxhkd &
dunst &
picom --config ~/.config/picom/picom.conf &
$HOME/.config/polybar/launch.sh &

$HOME/.fehbg &

xsetroot -cursor_name left_ptr &
setxkbmap -option ctrl:nocaps

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
