return {
    -- 'lukas-reineke/indent-blankline.nvim',
    -- main = 'ibl',
    -- opts = {
    --     scope = {
    --         enabled = true,
    --         show_start = true,
    --         show_exact_scope = true,
    --     },
    --     exclude = {
    --         filetypes = {
    --             'help',
    --             'startify',
    --             'dashboard',
    --             'packer',
    --             'neogitstatus',
    --             'NvimTree',
    --             'Trouble',
    --         },
    --     },
    -- },
}
